// <auto-generated />
using System;
using MafiaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MafiaAPI.Migrations
{
    [DbContext(typeof(MafiaDBContext))]
    [Migration("20210630121040_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Polish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MafiaAPI.Models.Agent", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BossId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Income")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Strength")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("BossId");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("MafiaAPI.Models.Boss", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Boss");
                });

            modelBuilder.Entity("MafiaAPI.Models.Message", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BossId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("id");

                    b.HasIndex("BossId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MafiaAPI.Models.Mission", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Loot")
                        .HasColumnType("int");

                    b.Property<string>("MissionName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Mission");
                });

            modelBuilder.Entity("MafiaAPI.Models.PerformingMission", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime");

                    b.Property<long?>("MissionId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("AgentId");

                    b.HasIndex("MissionId");

                    b.ToTable("PerformingMission");
                });

            modelBuilder.Entity("MafiaAPI.Models.Player", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BossId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nick")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("id");

                    b.HasIndex(new[] { "BossId" }, "UQ__Player__07C93FB72CC07189")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("MafiaAPI.Models.Agent", b =>
                {
                    b.HasOne("MafiaAPI.Models.Boss", "Boss")
                        .WithMany("Agents")
                        .HasForeignKey("BossId")
                        .HasConstraintName("FK__Agent__BossId__4BAC3F29");

                    b.Navigation("Boss");
                });

            modelBuilder.Entity("MafiaAPI.Models.Message", b =>
                {
                    b.HasOne("MafiaAPI.Models.Boss", "Boss")
                        .WithMany("Messages")
                        .HasForeignKey("BossId")
                        .HasConstraintName("FK__Message__BossId__66603565");

                    b.Navigation("Boss");
                });

            modelBuilder.Entity("MafiaAPI.Models.PerformingMission", b =>
                {
                    b.HasOne("MafiaAPI.Models.Agent", "Agent")
                        .WithMany("PerformingMissions")
                        .HasForeignKey("AgentId")
                        .HasConstraintName("FK__Performin__Agent__5165187F");

                    b.HasOne("MafiaAPI.Models.Mission", "Mission")
                        .WithMany("PerformingMissions")
                        .HasForeignKey("MissionId")
                        .HasConstraintName("FK__Performin__Missi__5070F446");

                    b.Navigation("Agent");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("MafiaAPI.Models.Player", b =>
                {
                    b.HasOne("MafiaAPI.Models.Boss", "Boss")
                        .WithOne("Player")
                        .HasForeignKey("MafiaAPI.Models.Player", "BossId")
                        .HasConstraintName("FK__Player__BossId__1DB06A4F")
                        .IsRequired();

                    b.Navigation("Boss");
                });

            modelBuilder.Entity("MafiaAPI.Models.Agent", b =>
                {
                    b.Navigation("PerformingMissions");
                });

            modelBuilder.Entity("MafiaAPI.Models.Boss", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Messages");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MafiaAPI.Models.Mission", b =>
                {
                    b.Navigation("PerformingMissions");
                });
#pragma warning restore 612, 618
        }
    }
}
